src/Entity/Equipment.php
<?php

namespace App\Entity;

use App\Enum\EquipmentType;
use App\Repository\EquipmentRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Doctrine\ORM\Mapping\InheritanceType;
use Gedmo\Mapping\Annotation\Loggable;
use Gedmo\Mapping\Annotation\Versioned;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: EquipmentRepository::class)]
#[InheritanceType('SINGLE_TABLE')]
#[DiscriminatorColumn(name: 'equipment_type', type: 'string')]
#[DiscriminatorMap([
    'yumi' => Yumi::class,
    'glove' => Glove::class,
])]
#[Loggable]

abstract class Equipment
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'owned_equipments')]
    #[Versioned]
    private ?Club $owner_club = null;

    #[ORM\ManyToOne(inversedBy: 'borrowed_equipments')]
    #[Versioned]
    private ?Club $borrower_club = null;

    #[ORM\ManyToOne(inversedBy: 'borrowed_equipments')]
    #[Versioned]
    private ?User $borrower_user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOwnerClub(): ?Club
    {
        return $this->owner_club;
    }

    public function setOwnerClub(?Club $owner_club): static
    {
        $this->owner_club = $owner_club;

        return $this;
    }

    public function getBorrowerClub(): ?Club
    {
        return $this->borrower_club;
    }

    abstract public static function getType(): EquipmentType;

    public function getTypeName(): string
    {
        return static::getType()->value;
    }

    public function setBorrowerClub(?Club $borrower_club): static
    {
        $this->borrower_club = $borrower_club;

        return $this;
    }

    public function getBorrowerUser(): ?User
    {
        return $this->borrower_user;
    }

    public function setBorrowerUser(?User $borrower_user): static
    {
        $this->borrower_user = $borrower_user;

        return $this;
    }
}

templates/equipement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EquipementController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Équipements</h1>

    <table border="1">
    <thead>
        <tr>
            <th>ID</th>
            <th>Type</th>
            <th>Club Propriétaire</th>
            <th>Club Emprunteur</th>
        </tr>
    </thead>
    <tbody>
        {% for equipement in equipements %}
            <tr>
                <td>{{ equipement.id }}</td>
                <td>{{ equipement.typeName }}</td>
                <td>
                {% if equipement.ownerClub %}
                   {{ equipement.ownerClub.name }}
                {% endif %}
                </td>
                <td>
                {% if equipement.borrowerClub %}
                   {{ equipement.borrowerClub.name }}
                {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}